# This defines a set of tools that are useful for configuring, debugging,
# or manipulating the network of a system.  It is desired to keep this list
# generic enough to be shared downstream with RHCOS.

packages:
  # Standard tools for configuring network/hostname
  - networkmanager-nmcli inetutils-hostname
  # Interactive Networking configuration during coreos-install
  - networkmanager-nmtui
  # Teaming https://github.com/coreos/fedora-coreos-config/pull/289
  # and http://bugzilla.redhat.com/1758162
  #- NetworkManager-team teamd
  # Support for cloud quirks and dynamic config in real rootfs:
  # https://github.com/coreos/fedora-coreos-tracker/issues/320
  - networkmanager-cloud-setup
  # Route manipulation and QoS
  - iproute2 iproute2-tc
  # Firewall manipulation
  - iptables nftables
  # Interactive network tools for admins
  #- socat net-tools bind-utils
  - socat net-tools
  # Declarative network configuration
  # https://github.com/coreos/fedora-coreos-tracker/issues/1175
  #- nmstate
  # Advanced custom networking calculations
  # https://github.com/coreos/fedora-coreos-tracker/issues/1460
  - ipcalc
