# This file is included in RHEL CoreOS, see
# https://github.com/openshift/os/blob/71c974b1e456292033e3ef3fe7bcfe17d1855ebc/manifest.yaml#L12
# Only apply changes here that should apply to both FCOS and RHCOS.

# Default to `bash` in our container, the same as other containers we ship.
container-cmd:
  - /usr/bin/bash

# These packages are either widely used utilities/services or
# are targeted for improving the general CoreOS user experience.
# It is intended to be kept generic so that it may be shared downstream with
# RHCOS.
packages:
  # Basic user tools
  ## jq - parsing/interacting with JSON data
  - bash-completion
  - coreutils
  - file
  - jq
  - less
  - sudo
  - vim-tiny
  # File compression/decompression
  ## bsdtar - dependency of 35coreos-live dracut module
  - bsdtar
  - bzip2
  - gzip
  - tar
  - xz
  - zstd
  # Improved MOTD experience
  #- console-login-helper-messages-issuegen
  #- console-login-helper-messages-profile
  # kdump support
  # https://github.com/coreos/fedora-coreos-tracker/issues/622
  - kexec-tools
  # Remote Access
  - openssh-ssh openssh-sshd
  # Container tooling
  ## crun recommends but doesn't require criu and criu-libs. We want them for
  ## checkpoint/restore. https://github.com/coreos/fedora-coreos-tracker/issues/1370
  #- crun criu criu-libs
  - crun criu libnet
  - podman
  - runc-docker
  - skopeo
  #- toolbox
  # passt provides user-mode networking daemons for namespaces
  #- passt
  # nvme-cli for managing nvme disks
  - nvme-cli
  # Used by admins interactively
  - lsof
