ref: wr/${basearch}/distro/${stream}
rojig:
  license: MIT
  name: wr-distro
  summary: Wind River Distro ${stream}

add-commit-metadata:
  wr-distro.stream: ${stream}


include: wr-distro-base.yaml

ostree-layers:
  - overlay/15fcos

automatic-version-prefix: "${releasever}.<date:%Y%m%d>.dev"
mutate-os-release: "${releasever}"

packages:
#  - busybox
   - coreutils
   - bash
   - base-files
   - dnf
   - libdnf
   - i2c-tools
   - iucode-tool
   - linuxptp
   - linuxptp-configs
   - lmsensors
   - os-release
#   - packagegroup-core-base-utils
   - rpm
   - rtl8723bs-bt
   - run-postinsts
   - dhcpcd
   - shadow
   - shadow-securetty
   - sed
   - grep
   - gawk
   - kmod
   - util-linux-flock
   - kernel-image-bzimage
   - kernel-modules
   - util-linux-findmnt
   - ostree-dracut
   - supermin
   - efivar
   - grub-bootconf
   - ldconfig
   - util-linux-umount
   - util-linux-losetup
   - util-linux-mount
   - util-linux-dmesg
   - util-linux-setsid
   - util-linux-nologin
   - util-linux-fstrim
   - util-linux-lsblk
   - util-linux-wipefs
   - util-linux-partx
   - util-linux-sfdisk
   - util-linux-su
   - dbus-broker
   - kbd
   - keyutils
   - libcap-ng
   - procps
   - coreos-installer
   - coreos-installer-bootinfra
   - diffutils
   - gptfdisk
   - bsdtar
   - policycoreutils-setfiles
   - e2fsprogs-resize2fs
   - e2fsprogs-tune2fs
   - 
etc-group-members:
  # Add the docker group to /etc/group
  # https://github.com/coreos/fedora-coreos-tracker/issues/2
  # This will be no longer needed when systemd-sysusers has been implemented:
  # https://github.com/projectatomic/rpm-ostree/issues/49
  - docker

# ⚠⚠⚠ ONLY TEMPORARY HACKS ALLOWED HERE; ALL ENTRIES NEED TRACKER LINKS ⚠⚠⚠
# See also the version of this in fedora-coreos-base.yaml
postprocess:

remove-from-packages:
  # Drop some buggy sysusers fragments which do not match static IDs allocation:
  # https://bugzilla.redhat.com/show_bug.cgi?id=2105177
#  - [dbus-common, /usr/lib/sysusers.d/dbus.conf]

remove-files:
  # We don't ship man(1) or info(1)
#  - usr/share/info
#  - usr/share/man
  # Drop text docs too
#  - usr/share/doc

# Things we don't expect to ship on the host.  We currently
# have recommends: false so these could only come in via
# hard requirement, in which case the build will fail.
exclude-packages:
#  - python
#  - python2
#  - python2-libs
#  - python3
#  - python3-libs
#  - perl
#  - perl-interpreter
#  - nodejs
#  - dnf
#  - grubby
#  - cowsay  # Just in case
  # Let's make sure initscripts doesn't get pulled back in
  # https://github.com/coreos/fedora-coreos-tracker/issues/220#issuecomment-611566254
#  - initscripts
  # For (datacenter/cloud oriented) servers, we want to see the details by default.
  # https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/HSMISZ3ETWQ4ETVLWZQJ55ARZT27AAV3/
#  - plymouth
  # Do not use legacy ifcfg config format in NetworkManager
  # See https://github.com/coreos/fedora-coreos-config/pull/1991
#  - NetworkManager-initscripts-ifcfg-rh
